module.exports = {
    "atc menu"  : "quote key next to the enter key",
    "autorudder": "control shift u",
    "capture a screenshot": "v",
    "exit"                : "control c",
    "exit immediately"    : "control pause",
    "joystick"            : "control k",
    "mission compass objective": "shift k",
    "mission compass pointer"  : "u",
    "pause": "p",
    "reset": "control plus",
    "save" : "semi-colon",
    "select item one"  : "1",
    "select item two"  : "2",
    "select item three": "3",
    "select item four" : "4",
    "decrease selection slightly" : "shift minus",
    "decrease selection"          : "minus",
    "increase selection slightly" : "shift equals",
    "increase selection"          : "equals",
    "simulation rate": "r",
    "slew mode"      : "y",
    "sound"          : "q",

    "trim ailerons left" : "control number pad 4",
    "trim ailerons right": "control number pad 6",
    "bank left" : "number pad 4",
    "bank right": "number pad 6",
    "trim elevator down": "number pad 7",
    "trim elevator up"  : "number pad 1",
    "lower flaps fully": "f8",
    "lower flaps"      : "f7",
    "raise flaps fully": "f5",
    "raise flaps"      : "f6",
    "center all flight controls": "number pad 5",
    "pitch down": "number pad 8",
    "pitch up"  : "number pad 2",
    "yaw left"  : "number pad 0",
    "yaw right" : "number pad enter",
    "trim rudder left" : "control number pad 0",
    "trim rudder right": "control number pad enter",
    "arm spoilers" : "shift forward slash",
    "spoilers"     : "forward slash",
    "water rudder" : "control w",

    "last item": "tbd. no comma on this one"
};
