module.exports = {
    "ATC menu": "quote key next to the enter key",
    "Autorudder": "Control Shift U",
    "Capture a Screenshot": "V",
    "Exit": "Control C",
    "Exit Immediately": "Control Pause",
    "Joystick": "Control K",
    "Mission compass objective": "Shift K",
    "Mission compass pointer": "U",
    "Pause": "P",
    "Reset": "Control Plus",
    "Save": "semi-colon",
    "Select item 1": "1",
    "Select item 2": "2",
    "Select item 3": "3",
    "Select Item 4": "4",
    "Decrease selection slightly": "Shift minus",
    "Decrease selection": "minus",
    "Increase selection slightly": "shift equals",
    "Increase selection": "equals",
    "Simulation Rate": "R",
    "Slew mode": "Y",
    "Sound": "Q",

    "Trim Ailerons left" : "Control Number pad 4",
    "Trim Ailerons right": "Control number pad 6",
    "Bank left" : "Number pad 4",
    "Bank right": "Number Pad 6",
    "Trim Elevator down": "Number pad 7",
    "Trim Elevator up"  : "Number pad 1",
    "lower flaps fully": "F8",
    "lower flaps"      : "F7",
    "raise flaps fully": "F5",
    "raise flaps"      : "F6",
    "center all flight controls": "Number pad 5",
    "pitch down": "Number pad 8",
    "pitch up"  : "Number pad 2",
    "yaw left"  : "Number pad 0",
    "yaw right" : "Number pad Enter",
    "Trim rudder left" : "Control Number pad 0",
    "Trim rudder right": "Control Number pad Enter",
    "Arm Spoilers": "Shift forward slash",
    "Spoilers"   s : "Forward Slash",
    "Water Rudder" : "Control W",

    "last item": "tbd. no comma on this one"
};
