module.exports = {
    "atc menu"  : "quote key next to the enter key",
    "autorudder": "control shift u",
    "capture a screenshot": "v",
    "exit"                : "control c",
    "exit immediately"    : "control pause",
    "joystick"            : "control k",
    "mission compass objective": "shift k",
    "mission compass pointer"  : "u",
    "pause": "p",
    "reset": "control plus",
    "save" : "semi-colon",
    "select item one"  : "1",
    "select item two"  : "2",
    "select item three": "3",
    "select item four" : "4",
    "decrease selection slightly" : "shift minus",
    "decrease selection"          : "minus",
    "increase selection slightly" : "shift equals",
    "increase selection"          : "equals",
    "simulation rate": "r",
    "slew mode"      : "y",
    "sound"          : "q",

    "trim ailerons left" : "control number pad 4",
    "trim ailerons right": "control number pad 6",
    "bank left" : "number pad 4",
    "bank right": "number pad 6",
    "trim elevator down": "number pad 7",
    "trim elevator up"  : "number pad 1",
    "lower flaps fully": "f8",
    "lower flaps"      : "f7",
    "raise flaps fully": "f5",
    "raise flaps"      : "f6",
    "center all flight controls": "number pad 5",
    "pitch down": "number pad 8",
    "pitch up"  : "number pad 2",
    "yaw left"  : "number pad 0",
    "yaw right" : "number pad enter",
    "trim rudder left" : "control number pad 0",
    "trim rudder right": "control number pad enter",
    "arm spoilers" : "shift forward slash",
    "spoilers"     : "forward slash",
    "water rudder" : "control w",

    "anti detonation tank valve" : "shift x",
    "arm autothrottle"    : "shift r",
    "engage autothrottle" : "control shift g",
    "toga"                : "control shift g",
    "carb heat"           : "h",
    "engine anti ice"     : "h",
    "reheat afterburners for the concorde" : "shift f4",
    "autostart engine" : "control e",
    "start the engine" : "control e",
    "engine"           : "e",
    "dump fuel"        : "control shift d",
    "magnetos"         : "m",
    "enrich mixture"   : "control shift f3",
    "mixture to full"  : "control shift f4",
    "mixture to cutoff": "control shift f1",
    "cut the mixture"  : "control shift f1",
    "quickly lean mixture" : "control shift f2",
    "nitrous tank valve"   : "shift c",
    "decrease propeller RPM quickly" : "control f2",
    "propeller rpm to high"  : "control f4",
    "increase propeller rpm" : "control f3",
    "propeller rpm to low"   : "control f1",
    "cut the throttle"       : "f1",
    "chop the throttle"      : "f1",
    "decrease throttle quickly" : "f2",
    "decrease throttle" : "number pad 3",
    "full throttle"     : "f4",
    "throttle to full"  : "f4",
    "increase throttle" : "f3 or number pad 9",

    "attach jetway"     : "control j",
    "detach jetway"     : "control j",
    "apply left brake"  : "number pad star",
    "apply right brake" : "number pad minus",
    "brakes"            : "period",
    "set the parking brake" : "control period",
    "clutch"            : "shift period",
    "close cowl flaps"  : "control shift c",
    "open cowl flaps"   : "control shift v",
    "dme one ident" : "control 4",
    "doors"         : "shift e",
    "end flight"    : "escape",
    "flying tips"   : "control shift x",
    "trigger a flying tips action" : "control x",
    "hoist arm"     : "control u",
    "lower the hoist cable"   : "j",
    "raise the hoist cable"  : "k",
    "attach the hoist hook"  : "o",
    "release the hoist hook" : "o",
    "attach the sling hook"  : "o",
    "release the sling hook" : "o",

    "manually extend the landing gear" : "control g",
    "landing gear"         : "g",
    "launch bar"           : "shift u",
    "master battery"       : "shift m",
    "alternator"           : "shift m",
    "mouse flight control" : "control y",
    "toggle pitch axis between normal and inverted" : "control shift i",
    "pushback" : "shift p",
    "release droppable objects" : "shift d",
    "request a fuel truck"  : "shift f",
    "apply the rotor brake" : "shift b",
    "rotor governor" : "shift comma",
    "smoke system"   : "l",
    "tail hook"      : "shift q",
    "tail wheel"     : "shift g",
    "takeoff assist"         : "shift i",
    "trigger takeoff assist" : "shift space",
    "request a tow plane" : "control shift y",
    "release the tow rope"  : "shift y",

    "last item": "tbd. no comma on this one"
};
